--- 
title: "R Scripts for Longitudinal and Panel Data"
author: "Yumo Dong, Edward Frees, and others??"
site: bookdown::bookdown_site
output:
  bookdown::gitbook
documentclass: book
bibliography: ["Bibliography/LDAReferenceC.bib"]
biblio-style: econPeriod
link-citations: yes
github-repo: https://github.com/openacttexts/Loss-Data-Analytics
description: "R scripts"
---

# Preface {-}

<p style="text-align:right;">
*Date: `r format(Sys.Date(), "%d %B %Y")`*</p>


This file contains `R` scripts for the book **Longitudinal and Panel Data** by Edward W. Frees. We will review these scripts in our [Panel and Copula Reading Group](https://sites.google.com/a/wisc.edu/copula-study-group/). To see the original scripts, go to the [book web site](https://instruction.bus.wisc.edu/jfrees/jfreesbooks/Longitudinal%20and%20Panel%20Data/Book/PDataBook.htm). At the same place, you will find the [datasets](https://instruction.bus.wisc.edu/jfrees/jfreesbooks/Longitudinal%20and%20Panel%20Data/Book/DataFiles.htm) that you can download. 

These scripts have been summarized by Yumo Dong into [R markdown](https://rmarkdown.rstudio.com/). Subsequently, Jed has put them together via [R bookdown](https://bookdown.org/yihui/bookdown/) and made them available to via [this Github respository](https://github.com/ewfreesRes/Long-Panel-Scripts). You may download the data from this site and view the code on the web [Github io site](https://ewfreesres.github.io/Long-Panel-Scripts/index.html).


As a group, it may be worth our time to update and polish these scripts. They were first done in 2003 and have not received a lot of cleansing since that time. If you contribute, then this will help polish your `R` skills, as well as learn a bit about `Github`. 

For more on actuarial education on the web through `Github`, see the [Open Actuarial Textbooks](https://ewfrees.github.io/) project. For `R` coding, see the [R Code for Loss Data Analytics](https://ewfrees.github.io/LDARcode/index.html) site.


